# your domain
domain: yeyulz.herokuapp.com
#domain: 127.0.0.1

# database dsn(postgresql)
# 暂不支持远程数据库，留空以启用本地数据库默认连接参数
database_url: ""

# cloudflare api
cf_email: ""
cf_key: ""

# source definition file
source-files:
  # use local file
  #- ./config/source.yaml
  # use web file
  - https://raw.githubusercontent.com/StevenFang/proxypool/master/config/source.yaml

# speedtest
speedtest: false  # default false. Warning: this will consume large net resource.
connection: 20    # default 20.
