# your domain
domain: yeyuws.tk
#domain: 127.0.0.1

# database dsn(postgresql)
# 暂不支持远程数据库，留空以启用本地数据库默认连接参数
database_url: ""

# cloudflare api
cf_email: "fang73573999@gmail.com"
cf_key: "QvpiMYQDZsrvb0Q8gxybtWZ7vB57IOlaDQh9-zhp"

# source definition file
source-files:
  # use local file
  - ./config/source.yaml
  # use web file
#  - https://example.com/config/source.yaml

# speedtest
speedtest: false  # default false. Warning: this will consume large net resource.
connection: 20    # default 20.
